# Generated by Django 5.1.6 on 2025-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('exams', 'Exams'), ('events', 'Events'), ('deadlines', 'Deadlines')], default='general', max_length=30),
        ),
    ]
